apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  nodeSelector:
    kubernetes.io/hostname: ip-10-0-1-147 # change it for your node ip
  containers:
  - image: ubuntu
    command:
    - echo 
    - "hello"
    - sleep
    - "100"
    name: test
    resources: {}
    securityContext:
      seccompProfile:
        type: Localhost
        localhostProfile: profiles/audit.json
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}